name: Update S&P 500 Forecast Chart

on:
  # Esegue ogni giorno alle 07:00 UTC
  schedule:
    - cron: '0 7 * * *'
  # Permette l'avvio manuale
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-forecast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script to generate forecast chart
        run: python generate_forecast.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add forecast.png
          git diff --staged --quiet || git commit -m "Auto-update S&P 500 forecast chart for $(date +'%Y-%m-%d')"
          git push
