name: Update Daily AI Roulette Tips

on:
  # Esegue ogni giorno alle 07:30 UTC
  schedule:
    - cron: '30 7 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-roulette:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script to generate roulette tips
        run: python generate_roulette.py
      - name: Commit and push roulette_tips.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add roulette_tips.json
          git diff --staged --quiet || git commit -m "Auto-update AI Roulette tips"
          git push
