name: Update Weekly Trader Mood

on:
  # Esegue ogni Lunedì alle 08:00 UTC
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-mood:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script to generate mood.json
        env:
          ALPHA_VANTAGE_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }}
        run: python generate_mood.py
      - name: Commit and push mood.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add mood.json
          git diff --staged --quiet || git commit -m "Auto-update Trader Mood data"
          git push
